#ifndef OOPBASICSINTRODUCTIONTOPROGRAMMINGPATTERNS_EXAMPLE_H
#define OOPBASICSINTRODUCTIONTOPROGRAMMINGPATTERNS_EXAMPLE_H

int example1();
int example2();
int example3();

#endif //OOPBASICSINTRODUCTIONTOPROGRAMMINGPATTERNS_EXAMPLE_H
