#ifndef OOPBASICSINTRODUCTIONTOPROGRAMMINGPATTERNS_FUSILIERY_H
#define OOPBASICSINTRODUCTIONTOPROGRAMMINGPATTERNS_FUSILIERY_H

#include "../Unite.h"


class Fusiliery : public Unite {
public:
    virtual void shoot(Unite*) final;
};


#endif //OOPBASICSINTRODUCTIONTOPROGRAMMINGPATTERNS_FUSILIERY_H
