#ifndef OOPBASICSINTRODUCTIONTOPROGRAMMINGPATTERNS_DAMAGETYPE_H
#define OOPBASICSINTRODUCTIONTOPROGRAMMINGPATTERNS_DAMAGETYPE_H

enum DamageType {
    cutting, pricking, crushing
};

#endif //OOPBASICSINTRODUCTIONTOPROGRAMMINGPATTERNS_DAMAGETYPE_H
